---
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: metadata
spec:
  image: flink:1.16
  flinkVersion: v1_16
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "20"
    jobmanager.web.submit.enable: "true"
  serviceAccount: flink
  podTemplate:
    apiVersion: v1
    kind: Pod
    metadata:
      name: pod-template
    spec:
      containers:
        - name: flink-main-container
          envFrom:
            - secretRef:
                name: subquery-db-prod3-env-secrets
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
